x-build-args: &python-build-args
  PYTHON_VERSION: ${PYTHON_VERSION:-3.13.10}

x-logging: &loki-logging
  driver: loki
  options:
    loki-url: 'http://loki:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},\d{3}) (?P<message>(?s:.*))$$'

name: taramonit

services:
  api:
    build:
      context: backend
      args:
        <<: *python-build-args
    depends_on:
      prometheus:
        condition: service_started
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    command: >
      sh -c "uvicorn --host=0.0.0.0 --port=80 taramonit.api:app --log-config=/app/log-config.yaml"
    healthcheck:
      test: [ "CMD", "python", "-c", "import socket; import sys; s=socket.socket(); s.settimeout(1); sys.exit(s.connect_ex(('localhost',80))>0)" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    logging: *loki-logging

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.28.0
    volumes:
      - ./blackbox_exporter/config.yml:/etc/blackbox_exporter/config.yml
    restart: always
    logging: *loki-logging

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always
    devices:
      - /dev/kmsg
    privileged: true

  certbot:
    image: certbot/certbot:v5.2.1
    volumes:
      - ./certbot/deploy-hook.sh:/deploy-hook.sh:ro,Z
      - certbot-certs:/etc/letsencrypt
      - certbot-www:/var/www/html
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
    command: >
      sh -c "trap exit TERM; while :; do
        certbot renew --webroot --webroot-path=/var/www/html --deploy-hook /deploy-hook.sh;
        sleep 12h;
      done"
    entrypoint: ""
    restart: always
    healthcheck:
      test: [ "CMD", "test", "-e", "/etc/letsencrypt/live/status.taram.ca/fullchain.pem" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 15
    logging: *loki-logging

  frontend:
    build:
      context: frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-}
    restart: always

  grafana:
    image: grafana/grafana:12.4.0-20047394513
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - certbot-certs:/etc/letsencrypt:ro
      - grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_PLUGINS_PREINSTALL=grafana-piechart-panel,grafana-clock-panel
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASS}
      - GF_SERVER_DOMAIN=status.taram.ca
      - GF_SERVER_ROOT_URL=https://status.taram.ca/grafana/
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_ENFORCE_DOMAIN=true
    networks:
      - default
      - taramail
      - taramux
      - tarawiki
    restart: always
    logging: *loki-logging

  loki:
    image: grafana/loki:3.5.9
    command: -config.file=/etc/loki/local-config.yaml

  nginx:
    build: nginx
    depends_on:
      api:
        condition: service_healthy
      certbot:
        condition: service_healthy
      frontend:
        condition: service_started
    volumes:
      - certbot-www:/web:ro
      - certbot-certs:/etc/letsencrypt:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:z
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - ADDITIONAL_SERVER_NAMES=${ADDITIONAL_SERVER_NAMES:-}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
    networks:
      default:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.240
      taramail:
      taramux:
      tarawiki:
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    depends_on:
      nginx:
        condition: service_started
    command:
      - '-nginx.scrape-uri=http://nginx:80/nginx_status'
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.8.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|run)($|/)"
      - "--collector.filesystem.fs-types-exclude=^(sysfs|proc|auto|cgroup.*|tmpfs|devpts|nsfs|overlay)$"
    restart: always
    pid: host

  prometheus:
    image: prom/prometheus:v3.8.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - default
      - taramail
      - taramux
      - tarawiki
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
    restart: always
    logging: *loki-logging

  tempo:
    image: grafana/tempo:2.9.0
    command:
      - "-config.file=/etc/tempo.yml"
      - "--target=all"
      - "--storage.trace.backend=local"
      - "--storage.trace.local.path=/var/tempo"
      - "--auth.enabled=false"
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
    depends_on:
      - loki
    logging: *loki-logging

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-taramonit
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
  taramail:
    external: true
    name: taramail_default
  taramux:
    external: true
    name: taramux_default
  tarawiki:
    external: true
    name: tarawiki_default

volumes:
  certbot-certs:
  certbot-www:
  grafana-data:
  prometheus-data:
