x-build-args: &python-build-args
  PYTHON_VERSION: ${PYTHON_VERSION:-3.13.10}

name: taramonit

services:
  alertmanager:
    image: prom/alertmanager:v0.30.1
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager-data:/alertmanager
    networks:
      taramail:
      default:
        aliases:
          - taramonit-alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
      - --web.external-url=https://${SERVER_HOSTNAME}/alertmanager
    restart: always

  alloy:
    image: grafana/alloy:v1.12.2
    depends_on:
      loki:
        condition: service_started
    volumes:
      - ./alloy/config.river:/etc/alloy/config.river:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      default:
        aliases:
          - taramonit-alloy
    command: [ "run", "/etc/alloy/config.river" ]
    restart: always

  api:
    build:
      context: backend
      args:
        <<: *python-build-args
    depends_on:
      prometheus:
        condition: service_started
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    networks:
      default:
        aliases:
          - taramonit-api
    command: >
      sh -c "uvicorn --host=0.0.0.0 --port=80 taramonit.api:app --log-config=/app/log-config.yaml"
    restart: always
    healthcheck:
      test: [ "CMD", "python", "-c", "import socket; import sys; s=socket.socket(); s.settimeout(1); sys.exit(s.connect_ex(('localhost',80))>0)" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.28.0
    volumes:
      - ./blackbox_exporter/config.yml:/etc/blackbox_exporter/config.yml
    networks:
      default:
        aliases:
          - taramonit-blackbox-exporter
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      default:
        aliases:
          - taramonit-cadvisor
    command:
      - '--docker_only=true'
      - '--enable_metrics=cpu,memory,network'
    restart: always
    devices:
      - /dev/kmsg
    privileged: true

  certbot:
    image: certbot/certbot:v5.2.2
    volumes:
      - ./certbot/deploy-hook.sh:/deploy-hook.sh:ro,Z
      - certbot-certs:/etc/letsencrypt
      - certbot-www:/var/www/html
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
    networks:
      default:
        aliases:
          - taramonit-certbot
    command: >
      sh -c "trap exit TERM; while :; do
        certbot renew --webroot --webroot-path=/var/www/html --deploy-hook /deploy-hook.sh;
        sleep 12h;
      done"
    entrypoint: ""
    restart: always
    healthcheck:
      test: [ "CMD", "test", "-e", "/etc/letsencrypt/live/${SERVER_HOSTNAME}/fullchain.pem" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 15

  frontend:
    build:
      context: frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-}
    networks:
      default:
        aliases:
          - taramonit-frontend
    restart: always

  grafana:
    image: grafana/grafana:12.4.0-20047394513
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - certbot-certs:/etc/letsencrypt:ro
      - grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/_home/home.json
      - GF_PLUGINS_PREINSTALL=grafana-piechart-panel,grafana-clock-panel,grafana-lokioperational-app
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASS}
      - GF_SERVER_DOMAIN=${SERVER_HOSTNAME}
      - GF_SERVER_ROOT_URL=https://${SERVER_HOSTNAME}/grafana/
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_ENFORCE_DOMAIN=true
      - GF_USERS_DEFAULT_THEME=light
    networks:
      taramail:
      taramux:
      tarawiki:
      default:
        aliases:
          - taramonit-grafana
    restart: always

  loki:
    image: grafana/loki:3.6.3
    networks:
      default:
        aliases:
          - taramonit-loki
    command:
      - '-config.file=/etc/loki/local-config.yaml'
      - '-ingester.min-ready-duration=0s'
    restart: always

  nginx:
    build: nginx
    depends_on:
      api:
        condition: service_healthy
      certbot:
        condition: service_healthy
      frontend:
        condition: service_started
    volumes:
      - certbot-www:/web:ro
      - certbot-certs:/etc/letsencrypt:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:z
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - ADDITIONAL_SERVER_NAMES=${ADDITIONAL_SERVER_NAMES:-}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
    networks:
      taramail:
      taramux:
      tarawiki:
      default:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.240
        aliases:
          - taramonit-nginx
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    depends_on:
      nginx:
        condition: service_started
    networks:
      default:
        aliases:
          - taramonit-nginx-exporter
    command:
      - '-nginx.scrape-uri=http://taramonit-nginx/nginx_status'
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.10.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave
    networks:
      default:
        aliases:
          - taramonit-node-exporter
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|run)($|/)"
      - "--collector.filesystem.fs-types-exclude=^(sysfs|proc|auto|cgroup.*|tmpfs|devpts|nsfs|overlay)$"
    restart: always
    pid: host

  prometheus:
    image: prom/prometheus:v3.9.1
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prometheus-data:/prometheus
    networks:
      taramail:
      taramux:
      tarawiki:
      default:
        aliases:
          - taramonit-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
    restart: always

  tempo:
    image: grafana/tempo:2.9.1
    depends_on:
      loki:
        condition: service_started
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
      - tempo-data:/var/tempo
    networks:
      default:
        aliases:
          - taramonit-tempo
    command:
      - '-config.file=/etc/tempo.yml'
      - '--target=all'
      - '--auth.enabled=false'
    restart: always

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-taramonit
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
  taramail:
    external: true
    name: taramail_default
  taramux:
    external: true
    name: taramux_default
  tarawiki:
    external: true
    name: tarawiki_default

volumes:
  alertmanager-data:
  certbot-certs:
  certbot-www:
  grafana-data:
  prometheus-data:
  tempo-data:
