global:
  scrape_interval: 30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api.taramonit_default:80']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://mail.taram.ca
          - https://wiki.taram.ca
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'federate-taramail'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~"probe|dovecot|rspamd|postfix"}'
        - 'dovecot_build_info'
        - 'rspamd_info'
    static_configs:
      - targets: ['prometheus.taramail_default:9090']

  - job_name: 'federate-tarawiki'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="probe"}'
    static_configs:
      - targets: ['prometheus.tarawiki_default:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

rule_files:
  - /etc/prometheus/rules/*.yml
