apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: (?:trace_id)=(\w+)
          matcherType: regex
          name: TraceID
          url: $${__value.raw}

  - name: taramail
    type: prometheus
    access: proxy
    uid: prometheus_taramail
    url: http://prometheus.taramail_default:9090
    editable: false
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: TraceID
      httpMethod: POST

  - name: taramonit
    type: prometheus
    access: proxy
    uid: prometheus_taramonit
    url: http://prometheus.taramonit_default:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: 30s

  - name: taramux
    type: prometheus
    access: proxy
    uid: prometheus_taramux
    url: http://prometheus.taramux_default:9090
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: 30s

  - name: tarawiki
    type: prometheus
    access: proxy
    uid: prometheus_tarawiki
    url: http://prometheus.tarawiki_default:9090
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: 30s

  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        customQuery: false
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: true
        tags:
          - key: service.name
            value: compose_service
