apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://taramonit-loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: (?:trace_id)=(\w+)
          matcherType: regex
          name: TraceID
          url: $${__value.raw}

  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://taramonit-tempo:3200
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        customQuery: false
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: true
        tags:
          - key: service.name
            value: compose_service

  - name: taramail
    type: prometheus
    access: proxy
    uid: taramail-prometheus
    url: http://taramail-prometheus:9090
    editable: false
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: TraceID
      httpMethod: POST

  - name: taramonit
    type: prometheus
    access: proxy
    uid: taramonit-prometheus
    url: http://taramonit-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: 30s

  - name: taramux
    type: prometheus
    access: proxy
    uid: taramux-prometheus
    url: http://taramux-prometheus:9090
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: 30s

  - name: tarawiki
    type: prometheus
    access: proxy
    uid: tarawiki-prometheus
    url: http://tarawiki-prometheus:9090
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: 30s
